version: '3'
services:
  node:
    image         : node:carbon
    container_name: Node
    build         : ./node
    ports:
      - "80:80"
  mongodb:
    image         : mongo:3.4
    container_name: Database
    build         : ./mongo
    ports:
      - "27017:27017"
